language: ruby
before_script:
  - gem update --system
  - gem install bundler
  - bundle exec sidekiq -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log -q default -q my_queue &
  - sleep 1
script: rspec spec
bundler_args: --without=extras
services:
  - redis-server
rvm:
  - jruby-19mode
  - rbx-2
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  allow_failures:
    - rvm: rbx-2
